//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonResource.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ebWebsiteEntities : DbContext
    {
        public ebWebsiteEntities()
            : base("name=ebWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerTrial_Form> CustomerTrial_Form { get; set; }
        public virtual DbSet<CustomerTrial_Info> CustomerTrial_Info { get; set; }
        public virtual DbSet<Ecommerce> Ecommerce { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<FooterInfo> FooterInfo { get; set; }
        public virtual DbSet<HomeBanner> HomeBanner { get; set; }
        public virtual DbSet<MainMenu> MainMenu { get; set; }
        public virtual DbSet<Meta> Meta { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PageContent> PageContent { get; set; }
        public virtual DbSet<PageContent_Mapping> PageContent_Mapping { get; set; }
        public virtual DbSet<PageUnit> PageUnit { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<TopMenu> TopMenu { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<TemporaryPageContent> TemporaryPageContent { get; set; }
    }
}
